version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.1

jobs: # ジョブの設定
  test:
    docker:
      - image: cimg/node:18.14.0
    # parallelism: 2 # 並列数を2で実行
    steps:
      - checkout # Githubからソースコードをチェックアウトする
      - restore_cache:
          keys:
            - node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install node packages # 依存関係のインストール
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: node-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Run lint and format # lint and format
          command: npm run lint && npm run format
      - run:
          name: Run Test # UIとE2E以外のテストを実行
          command: |
            npm test -- --shard=$(($CIRCLE_NODE_INDEX+1))/$CIRCLE_NODE_TOTAL src/chapter2/getting_started_jest src/chapter2/assertion src/chapter2/06_group src/chapter2/07_mock
      - store_test_results: # テスト結果をアップロード
          path: reports
      - store_artifacts: # カバレッジをアップロード
          path: reports/coverage

workflows: # ワークフローの設定
  test:
    jobs:
      - test
